version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: aaa111AAA
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: toor
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: